import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // SALES PRODUCTS
        {
            name: 'Steel Plates Set',
            rate: 500,
            category: 'Kitchen',
            productType: 'sales',
            stockQuantity: 25,
            minStockLevel: 5,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Pressure Cooker',
            rate: 1200,
            category: 'Kitchen',
            productType: 'sales',
            stockQuantity: 15,
            minStockLevel: 3,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Ceiling Fan',
            rate: 1800,
            category: 'Electronics',
            productType: 'sales',
            stockQuantity: 10,
            minStockLevel: 2,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Mixer Grinder',
            rate: 2500,
            category: 'Kitchen',
            productType: 'sales',
            stockQuantity: 12,
            minStockLevel: 3,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Water Purifier',
            rate: 8000,
            category: 'Home Appliances',
            productType: 'sales',
            stockQuantity: 5,
            minStockLevel: 1,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Induction Cooktop',
            rate: 3500,
            category: 'Kitchen',
            productType: 'sales',
            stockQuantity: 8,
            minStockLevel: 2,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Electric Kettle',
            rate: 800,
            category: 'Kitchen',
            productType: 'sales',
            stockQuantity: 20,
            minStockLevel: 5,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Room Heater',
            rate: 2200,
            category: 'Electronics',
            productType: 'sales',
            stockQuantity: 7,
            minStockLevel: 2,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // RENTAL PRODUCTS
        {
            name: 'Plastic Chairs',
            rate: 15,
            category: 'Furniture',
            productType: 'rental',
            stockQuantity: 200,
            minStockLevel: 50,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Banquet Tables',
            rate: 50,
            category: 'Furniture',
            productType: 'rental',
            stockQuantity: 50,
            minStockLevel: 10,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Wedding Tent',
            rate: 2000,
            category: 'Events',
            productType: 'rental',
            stockQuantity: 5,
            minStockLevel: 1,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sound System',
            rate: 1500,
            category: 'Audio/Video',
            productType: 'rental',
            stockQuantity: 8,
            minStockLevel: 2,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'DJ Equipment',
            rate: 3000,
            category: 'Audio/Video',
            productType: 'rental',
            stockQuantity: 3,
            minStockLevel: 1,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'LED Stage Lights',
            rate: 800,
            category: 'Events',
            productType: 'rental',
            stockQuantity: 10,
            minStockLevel: 2,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Projector & Screen',
            rate: 1200,
            category: 'Audio/Video',
            productType: 'rental',
            stockQuantity: 4,
            minStockLevel: 1,
            totalSales: 0,
            totalRentals: 0,
            lastRestocked: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});